### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by Bashamega** [BwnnyRxbbit/ScratchFind#12]
Hello:)
I saw your project and noticed some problems with style:

1. The border for the button looks weird.
2. The cursor is not pointer some people will think the button is disabled.
3. The Select menu lacks moder looks
4. In dark mode when you search the text is white so you can see it.
5. The output is not styled and hard to read
6. The theme switcher can be replaced with icons.

I would like to work on this

**Comment by BwnnyRxbbit** [comment]
Ok, go ahead!

**Comment by BwnnyRxbbit** [comment]
I've personally fixed number 2.

**Comment by BwnnyRxbbit** [comment]
Can you have a look at this? https://github.com/BwnnyRxbbit/clock-app/discussions/1
